---
title: "Lab 14 Homework"
author: "Tatiana Aguilar"
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: spacelab
    toc: yes
    toc_float: yes
    keep_md: yes
---

## Lab 14 Binder
If you want to return to the binder, find the [repository and instructions here](https://github.com/hehouts/lab14_binder)

## Instructions
Answer the following questions in RMarkdown. Please embed all of your code and push your final work to your repository. Be sure to add your name to the author header above.



## Questions

1. Look up 'Data Scientist' at https://www.bls.gov/. What degree is required for this career? Is it a growing occupation?  

Data Scientisthave a Bachelor's degree. It is a growing occupation.

2. How would you describe your data science skills on a resume for a job application? Write a blurb that reflects the skills you have learned in this course. 

  Can create apps and visualizations from data using R programming languages. Can manipulate data in R, able to add multiple data sets into one location.
  
3. What are your current career interests, and how could your R skills support that career path? (hint: this might be good content for your LinkedIn profile ;)

  I am currently interested in pursing a career as a forensic geneticist. R skills will help me in the lab setting and is why I took this class.
  
4. What about this course has been the most difficult for you? What has been the most rewarding?

  The most difficult material in this class has been shiny apps but at the same time it is really rewarding being able to make a simple app. 

5. What do you wish you had known, or what skills do you wish you had, before taking this class.

  I think I wish I had known more basic computer skills.


6. If we had 1 more lab in this class, what would you have liked to learn more about?

  I think we covered everything that I wanted to learn with R, at least for just one quarter of class.

7. Now that you have (almost!) completed this course, do you plan to persue further data or computer science skills? What do you plan to do?

  I do want to continue learning more data science especially in a lab setting. Hopefully I can start as a student assistant in a lab using my skills.

8. How important was working with a partner to your success in this class? If this class were transitioned to an online format, how do you think that would affect your understanding?

  I think having someone, not necessarily a partner helped me understand the class better. I have actually done some of the labs virtually and was able to complete them altough a live zoom section would definitely help.

9. Did you complete the class evaluation? Please complete the class evaluation using the link provided in the announcements. Your feedback is very important and we appreciate your time.

  Yes I did.

## Push your final code to GitHub!
Please be sure that you check the `keep md` file in the knit preferences. 
