---
title: "Lab 3 Warmup"
author: "Tatiana Aguilar"
date: "2023-01-17"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Plant Height
```{r}
plant_height <- c(30.7, 37.6, 28.4, NA, 33.2)
```

### 2. Plant Weight
```{r}
plant_weight <- c(4, 5.2, 3.7, NA, 4.6)
```

### 3. Label Data Matrix
```{r}
samples <- c("plant1", "plant2", "plant3", "plant4", "plant5")
measured <- c("height", "weight")
```

### 4. Combine data for height and weight
```{r}
plant_experiment <- c(plant_height, plant_weight)
plant_experiment
```

### 5. Build the data matrix
```{r}
plant_experiment_matrix <- matrix(plant_experiment, nrow = 5,byrow = F)
plant_experiment_matrix
```

### 6. Name coulumns and rows
```{r}
colnames(plant_experiment_matrix) <- measured
rownames(plant_experiment_matrix) <- samples
```

### 7. Print the matrix
```{r}
plant_experiment_matrix
```

### 8. Calculate column means
```{r}
plant_means <- colMeans(plant_experiment_matrix, na.rm = T)
plant_means
```

### 9. Add this column to the matrix
```{r}
plant_experiment_matrix_final <- rbind(plant_experiment_matrix, plant_means)
```

### 10. Print the final version
```{r}
plant_experiment_matrix_final
```
